### PR TITLE
CSOPS-1030: Update comment in Hora.js to account for different currencies

### PR DESCRIPTION
**Pull request by levindixon**
Status: **Opened for visibility**
Reviewers: **@scalvert @Helen-Mobify**
JIRA: [CSOPS-1030](https://mobify.atlassian.net/browse/CSOPS-1030)
  
## Changes
- Comment updated to clarify that currency can be set.

### CODE REVIEW

**Comment by scalvert** [comment]
Should we also add a link to the google analytics docs?

**Comment by levindixon** [comment]
Sure! How should it read? 

For more information please see: 
https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce

**Comment by levindixon** [comment]
@scalvert I've added the link to GA's Ecommerce Tracking docs.

**Comment by scalvert** [comment]
:+1:

**Pull request merged**
