### PR TITLE
Add View Desktop click event tracking

### PR DESCRIPTION
**Pull request by marlowpayne**
Status: **Ready for Review**
Owner: @marlowpayne
Reviewers: @ericmuyser @scalvert @Helen-Mobify 

## Changes
- Carnival has asked us to track clicks on their "View Desktop" link. I have added this as a general Hora event for tracking.

## Jira Tickets:
- https://mobify.atlassian.net/browse/CCL-435

## Todos:
- [ ] Engineer +1

### Feedback:
_none so far_

## How to Test
- Checkout this branch
- Run `grunt test` and/or `grunt test:browser`
- Make sure the code makes sense

### CODE REVIEW

**Comment by scalvert** [comment]
Just as an FYI we're trying to limit additions to Hora in general right now until we can take a look at it closer to see what's needed and what's not. Helen is also working on a branch that cleans out some of the more specific functions. I think her changes would accommodate what you need.

@Helen-Mobify what's the status of that branch?

**Comment by ericmuyser** [comment]
Hmm, I would recommend just doing `Hora.send('View Desktop', 'Click');` for now (and in other situations) rather than creating a new event function.

**Comment by marlowpayne** [comment]
Sounds good guys. Thanks.

**Comment by Helen-Mobify** [comment]
Looks like this is resolved. Closing PR.

**Pull request closed without merging**
